#!/usr/bin/env python3
"""
Scans numbered markdown package files (e.g. 00-environment-setup.md,
01-linux-headers.md, ...) anywhere in the repo and generates PROGRESS.md
summarizing what's documented so far.

Run manually with: python3 scripts/generate_progress.py
Run automatically by: .github/workflows/update-progress.yml
"""

import re
from pathlib import Path
from datetime import datetime, timezone

REPO_ROOT = Path(__file__).resolve().parent.parent
OUTPUT_FILE = REPO_ROOT / "PROGRESS.md"

# Matches filenames like "Package_001_Linux_Headers(00-linux-headers).md",
# "Package_007_GCC(Pass2).md"
NUMBERED_FILE_RE = re.compile(r"^Package_(\d+)_(.+)\.md$")

# Skip these when scanning — not package/step files
SKIP_NAMES = {
    "PROGRESS.md", "README.md", "GETTING_STARTED.md",
    "ALL_STARTS_HERE.md", "Enviornment-Setup.md", "Overview_Main.md",
}


def find_package_files():
    """Find all numbered .md files anywhere under the repo, excluding .github and node_modules."""
    matches = []
    for path in REPO_ROOT.rglob("*.md"):
        if ".github" in path.parts or "node_modules" in path.parts:
            continue
        if path.name in SKIP_NAMES:
            continue
        m = NUMBERED_FILE_RE.match(path.name)
        if m:
            matches.append((int(m.group(1)), path))
    matches.sort(key=lambda x: x[0])
    return matches


def extract_title(text: str, fallback: str) -> str:
    m = re.search(r"^#\s+(.+)$", text, re.MULTILINE)
    return m.group(1).strip() if m else fallback


def extract_why(text: str) -> str:
    m = re.search(r"\*\*Why[^:]*:\*\*\s*(.+)", text)
    if m:
        line = m.group(1).strip()
        # trim to a reasonable summary length
        return (line[:140] + "…") if len(line) > 140 else line
    return "—"


def has_commit_checkpoint(text: str) -> bool:
    return bool(re.search(r"^##\s*Commit checkpoint", text, re.MULTILINE))


def count_known_issues(text: str) -> int:
    # Counts documented warning/known-issue callouts ( headers or "Known issue" headers)
    warning_headers = re.findall(r"^##\s*.*$", text, re.MULTILINE)
    known_issue_headers = re.findall(r"^##.*Known [Ii]ssue.*$", text, re.MULTILINE)
    return len(warning_headers) + len(known_issue_headers)


def extract_next(text: str) -> str:
    m = re.search(r"^##\s*Next\s*\n+(.+?)(?:\n##|\Z)", text, re.MULTILINE | re.DOTALL)
    if not m:
        return "—"
    next_text = m.group(1).strip()
    # pull out a backtick-quoted filename if present, otherwise first line
    fm = re.search(r"`([^`]+)`", next_text)
    if fm:
        return fm.group(1)
    return next_text.splitlines()[0].strip()


def build_progress_markdown(entries):
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    lines = []
    lines.append("# Project Progress\n")
    lines.append(f"_Auto-generated by `scripts/generate_progress.py` — last updated {now}._\n")
    lines.append(
        "This file is regenerated automatically on every push that touches a "
        "markdown file. Don't hand-edit it — edit the individual package/doc "
        "files instead, and this will pick up the changes on the next push.\n"
    )

    total = len(entries)
    documented = sum(1 for e in entries if e["documented"])
    total_issues = sum(e["known_issues"] for e in entries)

    lines.append(f"**Steps documented:** {documented}/{total}  ")
    lines.append(f"**Known issues captured across all steps:** {total_issues}\n")

    lines.append("| # | File | Title | Why (summary) | Documented | Known Issues | Next |")
    lines.append("|---|------|-------|----------------|------------|--------------|------|")

    for e in entries:
        doc_mark = "" if e["documented"] else "⬜"
        lines.append(
            f"| {e['num']:02d} | `{e['relpath']}` | {e['title']} | {e['why']} | "
            f"{doc_mark} | {e['known_issues']} | {e['next']} |"
        )

    lines.append("")
    lines.append("## Legend")
    lines.append("- **Documented** — the file has a `## Commit checkpoint` section, meaning the step was actually carried out and verified, not just planned.")
    lines.append("- **Known Issues** — count of `` or \"Known issue\" callouts in that file, i.e. real bugs hit and fixed during that step.")

    return "\n".join(lines) + "\n"


def main():
    files = find_package_files()
    entries = []

    for num, path in files:
        text = path.read_text(encoding="utf-8", errors="ignore")
        relpath = path.relative_to(REPO_ROOT)
        entries.append({
            "num": num,
            "relpath": str(relpath),
            "title": extract_title(text, fallback=path.stem),
            "why": extract_why(text),
            "documented": has_commit_checkpoint(text),
            "known_issues": count_known_issues(text),
            "next": extract_next(text),
        })

    output = build_progress_markdown(entries)
    OUTPUT_FILE.write_text(output, encoding="utf-8")
    print(f"Wrote {OUTPUT_FILE} with {len(entries)} entries.")


if __name__ == "__main__":
    main()
